language: android

jdk: oraclejdk8

env:
  matrix:
    - ANDROID_API_LEVEL=22 ANDROID_ABI=armeabi-v7a
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10
    - ANDROID_TAG=google_apis
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    - android-$ANDROID_API_LEVEL

    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # System images
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL


sudo: required

before_script:
  - echo no | android create avd --force -n test -t "android-"$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew library:connectedAndroidTest
