version: 2
jobs:

  build_test:
    resource_class: large
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx3096m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3096m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout

      - run:
          name: Generate cache key
          command: ./.scripts/checksum.sh /tmp/checksum.txt

      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          no_output_timeout: 30m

      - run:
          name: Run Tests
          command: ./gradlew test
          no_output_timeout: 30m

      - save_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test
